name: NCAA Baseball Data Collection

on:
  schedule:
    - cron: "0 8 * * *" # Runs at 8:00 UTC daily
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ${{ github.workspace }}/R/library

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Install R dependencies
        run: |
          install.packages(c(
            "dplyr",
            "purrr",
            "tidyverse",
            "httr",
            "rvest",
            "DBI",
            "RSQLite",
            "cli",
            "xml2",
            "devtools"
          ), repos = "https://cloud.r-project.org/")
          devtools::install_github(repo = "robert-frey/collegebaseball")
        shell: Rscript {0}

      - name: Run data collection scripts
        run: |
          Rscript -e 'source("scrapers/collect_schedules.R"); main(working_dir = getwd(), output_dir = file.path(getwd(), "data/schedules"))'

          Rscript -e 'source("scrapers/collect_pbp.R"); main(working_dir = file.path(getwd(), "data/schedules"), output_dir = file.path(getwd(), "data/play_by_play"))'

          Rscript -e 'source("scrapers/collect_stats.R"); main(working_dir = getwd(), output_dir = file.path(getwd(), "data/stats"))'
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git commit -m "Update pbp, stats" || echo "No changes to commit"
          git push
