name: NCAA Baseball Data Collection

on:
  schedule:
    - cron: "0 8 * * *" # Runs at 8:00 UTC daily
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      R_LIBS_USER: ${{ github.workspace }}/R/library
      DATA_DIR: data
      SCHEDULES_DIR: data/schedules
      PBP_DIR: data/play_by_play
      STATS_DIR: data/stats

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages("remotes")
          remotes::install_cran(c(
            "dplyr",
            "purrr",
            "tidyverse",
            "httr",
            "rvest",
            "DBI",
            "RSQLite",
            "cli",
            "xml2",
            "devtools",
            "pacman"
          ), dependencies = TRUE)
          remotes::install_github(repo = "robert-frey/collegebaseball")
          remotes::install_github(repo = "billpetti/baseballr")
        shell: Rscript {0}

      - name: Run data collection scripts
        shell: Rscript {0}
        run: |
          # Set working directory to repository root
          root_dir <- getwd()

          # Collect schedules
          source('scrapers/collect_schedules.R')
          main(working_dir = root_dir, output_dir = file.path(root_dir, '${{ env.SCHEDULES_DIR }}'))

          # Collect play-by-play data
          source('scrapers/collect_pbp.R')
          main(working_dir = file.path(root_dir, '${{ env.SCHEDULES_DIR }}'), 
               output_dir = file.path(root_dir, '${{ env.PBP_DIR }}'))

          # Collect stats
          source('scrapers/collect_stats.R')
          main(working_dir = root_dir, 
               output_dir = file.path(root_dir, '${{ env.STATS_DIR }}'))

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ env.DATA_DIR }}/
          git commit -m "Update pbp, stats" || echo "No changes to commit"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
