name: Get NCAA IDs

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

concurrency:
  group: ncaa-scraper
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      DATA_DIR: data

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 tqdm

      - name: Run scraper
        id: scraper
        timeout-minutes: 290
        continue-on-error: true
        run: |
          python scrapers/get_all_ids.py --data_dir ${{ env.DATA_DIR }}

      - name: Commit and push progress
        if: always()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add data/
          git commit -m "Updated ids" || echo "No changes to commit"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      # Final cleanup step
      - name: Cleanup
        if: always()
        run: |
          # Add any cleanup tasks here
          echo "Scraper completed with status: ${{ steps.scraper.outcome }}"
