name: NCAA Baseball Data Processing

on:
  workflow_run:
    workflows: ["NCAA Baseball Data Collection"]
    types:
      - completed
  workflow_dispatch: # Allows manual triggering

jobs:
  process-data:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ${{ github.workspace }}/R/library

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install R dependencies
        run: |
          install.packages(c(
            "tidyverse",
            "cli",
            "remotes",
            "collegebaseball"
          ), repos = "https://cloud.r-project.org/")
        shell: Rscript {0}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Parse PBP data
        run: |
          source("processors/parse_pbp.R")
          main(
            working_dir = getwd(),
            data_dir = file.path(getwd(), "data")
          )
        shell: Rscript {0}

      - name: Guts constants
        run: |
          python processors/get_guts.py \
            --data_dir ${{ github.workspace }}/data

      - name: Generate leaderboards
        run: |
          python processors/get_leaderboards.py \
            --data_dir ${{ github.workspace }}/data

      - name: Get expected runs matrix
        run: |
          python processors/get_er_matrix.py \
            --data_dir ${{ github.workspace }}/data

      - name: Get linear weights
        run: |
          python processors/get_linear_weights.py \
            --data_dir ${{ github.workspace }}/data

      - name: New parsed pbp with leverage, win exp
        run: |
          python processors/add_pbp_metrics.py \
            --data_dir ${{ github.workspace }}/data

      - name: Calculate WAR
        run: |
          python processors/add_war.py \
            --data_dir ${{ github.workspace }}/data

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git commit -m "Update processed baseball data" || echo "No changes to commit"
          git push
