name: DB Update

on:
  workflow_run:
    workflows: ["NCAA Baseball Data Processing"]
    types:
      - completed
  workflow_dispatch:

jobs:
  db_update:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    env:
      DB_PATH: /home/ubuntu/d3_dashboard/backend/ncaa.db
      DATA_DIR: /home/ubuntu/d3_dashboard/backend/data

    steps:
      - name: Copy Data and Update Databases
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clone or update pipeline repository
            if [ -d "d3_pipeline" ]; then
              cd d3_pipeline
              git pull
            else
              git clone https://${GITHUB_TOKEN}@github.com/jack-kelly-12/d3_pipeline.git
              cd d3_pipeline
            fi

            # Create directories and set permissions
            sudo mkdir -p /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/data
            sudo mkdir -p /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend
            sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} /home/${{ secrets.EC2_USERNAME }}/d3_dashboard

            # Create database directory if it doesn't exist
            sudo mkdir -p $(dirname /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/ncaa.db)
            sudo touch /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/ncaa.db
            sudo chown ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/ncaa.db

            # Copy data files and update script
            cp -r data/* /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/data/
            cp update_database.py /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/

            # Run update script
            cd /home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend
            source venv/bin/activate
            python3 update_database.py \
              --data_dir "/home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/data" \
              --db_path "/home/${{ secrets.EC2_USERNAME }}/d3_dashboard/backend/ncaa.db"
